<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MoreVasanthKumar" failures="2" tests="2" name="Default test" time="21.04" errors="0" timestamp="2023-11-07T18:02:03 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.339">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.StepDefinitions.LoginStepDef.user_enters_user_name_and_password(LoginStepDef.java:23)
at ✽.user enters userName and password(file:///C:/Users/SPUGE/git/cucumberE2E/CucumberProject/src/test/resources/FeatureFiles/LoginFeature.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.335">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.StepDefinitions.LoginStepDef.user_enters_user_name_and_password(LoginStepDef.java:23)
at ✽.user enters userName and password(file:///C:/Users/SPUGE/git/cucumberE2E/CucumberProject/src/test/resources/FeatureFiles/LoginFeature.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
